language: go

go:
    - "1.8"
    - "1.9"
    - "1.10"
    - "1.11"

before_install:
    - go get github.com/streadway/amqp
    - go get github.com/jc3wish/RabbitMQTest/src

install:
    - go get github.com/mattn/goveralls

script:
    - go test -v -covermode=count -coverprofile=coverage.out
    - go build RabbitMQTest.go


after_success:
  - goveralls -coverprofile=full_cov.out -service=travis-ci